const menuList = [
    {
        title:'首页',
        path:"1",
        icon:"home"
    },
    {
        title:'UI',
        path:'2',
        icon:"button",
        children:[
            {
                title:'按钮',
                path:'sddsf',
            },
            {
                title:'弹框',
                path:'sf',
            },
            {
                title:'loading',
                path:'sdsf',
            },
            {
                title:'通知提醒',
                path:'dsf',
            },
            {
                title:'全局Message',
                path:'全局message',
            },
            {
                title:'Tab页签',
                path:'Tab页签',
            },
            {
                title:'图片画廊',
                path:'图片画廊',
            },
            {
                title:'轮播图',
                path:'轮播图',
            },
        ],
    },
    {
        title:'表单',
        path:'3',
        icon:"",
        children:[
            {
                title:"登陆",
                key:"登陆"
            },
            {
                title:"注册",
                key:'注册'
            }
        ]
    },
    {
        title:'表格',
        path:'4',
        icon:"",
        children:[
            {
                title:"基础表格",
                key:"基础表格"
            },
            {
                title:"高级表格",
                key:'高级表格'
            }
        ]
    },
    {
        title:'富文本',
        path:'5',
        icon:""
    },
    {
        title:'城市管理',
        path:'6',
        icon:""
    },
    {
        title:'订单管理',
        path:'7',
        icon:""
    },
    {
        title:'员工管理',
        path:'8',
        icon:""
    },
    {
        title:'车辆地图',
        path:'9',
        icon:""
    },
    {
        title:'图标',
        path:'10',
        icon:"",
        children:[
            {
                title:"柱形图",
                key:'柱形图',
            },
            {
                title:'饼图',
                key:'饼图'
            }
        ]
    },
    {
        title:'权限控制',
        path:'11',
        icon:""
    },
];
export default menuList;